### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by HDaoud** [openalpr/imageclipper#2]
Hi,

I was having errors when "make", it's related to **BEGIN**   and   **END** not defined and another errors related to CV_ASSERT, however, when I added the following to header files raising the error, it was solved.
# define **BEGIN**       {
# define **END**         goto exit; exit: ; }

/_proceeds to "resource release" stage_/
# define EXIT            goto exit

Why is that although the cxcore is included where these macros should be defined.

**Comment by CiprianMo** [comment]
@HDaoud I'm getting the same errors, as I'm not really familiar with C++, would you please explain in more details where do i have to define these labels ?

**Comment by HDaoud** [comment]
Hi @CiprianMo 

I don't really remember the error, and it's my bad I didn't post it here, however, try to read in the error and see which files are raising it, the error usually clear and shows the line number and the stack trace of error. once you confirm the names of header files (as it appears it was in multiple header files from my comment above) open them and add the above code and recompile.

Hope that helps!

**Comment by CiprianMo** [comment]
Hi @HDaoud,
Thank you for the quick response, you were correct the errors tell me in which files i need to add these lines but I figure out where exactly i had to add them? 
By the way the errors say that **BEGIN**, **END** are not declared in the scope and that label 'exit' is used but not defined CV_ASSERT( rect.width > 0 && rect.height > 0 );

I imagine that #define BEGIN and #define END goto exit; exit: ;  should go on top of the header and  #define EXIT goto exit should go on the bottom.

Thank you again for your help

**Comment by CiprianMo** [comment]
OK so i found what the problem was. In the directory imageclipper-master/src/opencvx/ there are 3 header files: cvcreateaffine.h, cvcropimageroi.h and cvdrawrectangle.h where ****BEGIN**** and ****END**** have to be changed to ****CV_BEGIN**** and ****CV_END****. 
Because the opencv that i installed has a header core_c.h where ****CV_BEGIN**** and ****CV_END**** defined and used later in the above mentioned headers of the imageclipper.
I'm guessing this happened because the opencv i installed is a newer version of the one Mattew has

I hope this helps others with the same problem

**Comment by HDaoud** [comment]
I'm glad that you solved it, I will close this issue.
